name: Node.js CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.16.0]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: cd ./examples/typescript-angular && pwd && ls -la
    - run: npm i  
    - run: npm install drill4js-cli --save-dev
    - run: npx drill4js-cli -sc .drill4rc-remote
      env:
        CI: true
